---
# handlers file for setup-apache

- name: start_apache
  service:
    name: httpd
    state: started

- name: start_apache2
  service:
    name: apache2
    state: started

- name: restart_apache
  service:
    name: httpd
    state: restarted

- name: restart_apache2
  service:
    name: apache2
    state: restarted

        
