---
- name: This playbook task is to create a new user as per the host file information  
  hosts: all
  become: true
  vars_files:
    - user_variable.yml
  tasks:
  - name: creating new user {{ user }}
    user: 
      name: "{{ user }}"
