---
- name: This playbook is to install packages via YUM command and it is coded by Abuthahir
  hosts: webserversrhel
  become: true
  tasks:
  - name: Install HTTPD package
    yum: 
     name: httpd
     state: installed
    notify: Start HTTPD Service
  handlers:   
  - name: Start HTTPD Service
    service:
      name: httpd
      state: started     
