---
- name: This playbook is to install apache package via apt command in UBUNTU server and it is coded by Abuthahir
  hosts: databaseserverubuntu
  become: true
  tasks:
  - name: Install apache2 package
    apt: 
     name: apache2
     state: present
     tags: install_apache

  - name: Start apache2 Service
    service:
      name: apache2
      state: started  
      tags: start_apache   
