---
- name: This playbook is to install multiple packages via YUM command and it is coded by Abuthahir
  hosts: webserversrhel
  become: true
  tasks:
  - name: Install HTTPD package
    yum: 
    # name: ['git', 'gzip', 'make', 'wget','telnet', 'gcc']
     name: "{{ item }}"  
     state: installed
    with_items:
            - git
            - make
            - gzip
            - telnet
            - gcc
 
          
