---
- name: This playbook is to install apache packages by determining OS family and it is coded by Abuthahir
  hosts: all
  become: true
  vars:
    port: 8081
  tasks:
  - name: Install HTTPD package
    yum: 
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"
    notify: start_apache
    

  - name: Install apache2 service
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: start_apache2

  - name: Copy HTML file to apache server page
    copy:
       src: /opt/ansible/index.html
       dest: /var/www/html
       mode: 0666
  - name: Ensure the default Apache port is {{ port }}
    ansible.builtin.lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^Listen '
       insertafter: '^#Listen '
       line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart_apache

  - name: Ensure the default Apache port is {{ port }} on UBUNTU server
    ansible.builtin.lineinfile:
       path: /etc/apache2/ports.conf
       regexp: '^Listen '
       insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
       line: Listen {{ port }}
    when: ansible_os_family == "Debian"
    notify: restart_apache2

  handlers:
  - name: start_apache 
    service:
      name: httpd
      state: started   
    

  - name: start_apache2
    service:
      name: apache2
      state: started

  - name: restart_apache
    service:
      name: httpd
      state: restarted

  - name: restart_apache2   
    service:
      name: apache2
      state: restarted      
